const mongoose = require('mongoose');

const tripDetailsSchema = new mongoose.Schema({
    TruckNumber:{
        type:String,
        required:true,
        trim:true
    },
    DONumber:{
        type:Number,
        required:true,
        trim:true
    },
    DriverName:{
        type:String,
        required:true,
        trim:true
    },
    Vendor:{
        type:String,
        required:true
    },
    DestinationFrom:{
        type:String,
        required:true
    },
    DestinationTo:{
        type:String,
        required:true
    },
    TruckType:{
        type:String,
        required:true
    },
    TransactionStatus:{
        type:String,
        required:true
    },
    Weight:{
        type:Number,
        required:true
    },
    Freight:{
        type:Number,
        required:true
    },
    ActualWeight:{
        type:Number,
        default:null
    },
    DifferenceInWeight:{
        type:Number,
        default:null
    },
    Freight:{
        type:Number,
        required:true
    },
    Diesel:{
        type:Number,
        required:true
    },
    DieselAmount:{
        type:Number,
        required:true
    },
    DieselSlipNumber:{
        type:Number,
        required:true
    },
    TDS_Rate:{
        type:Number,
        required:true
    },
    Advance:{
        type:Number,
        required:true
    },
    Toll:{
        type:Number,
        required:true 
    },
    Adblue:{
        type:Number,
        required:true
    },
    Greasing:{
        type:Number,
        required:true
    },
    BillId:{
        type:Number,
        default:null
    },
    DieselSlipImage:{
        filepath:{type:String,default:null},
        originalname:{type:String,default:null}
    },
    LoadingAdvice:{
        filepath:{type:String,default:null},
        originalname:{type:String,default:null}
    },
    InvoiceCompany:{
        filepath:{type:String,default:null},
        originalname:{type:String,default:null}
    },
    WeightmentSlip:{
        filepath:{type:String,default:null},
        originalname:{type:String,default:null}
    },


},{timestamps:true});




  module.exports = mongoose.model('TripDetails',tripDetailsSchema);
